### ISSUE TITLE
Wrong Mapping for ldap_389ds_scrape_interval

### ISSUE THREAD

**Issue by daviddelannoy** [ggatward/ansible-389ds-exporter#1]
https://github.com/ggatward/ansible-389ds-exporter/blob/1fe9e176f1ce2dcfae843ed81fea5a43c1171435/templates/389ds_exporter.yml.j2#L6

Hi @ggatward , useful role :+1: 
I'm using it. Currently facing some problems with space in `'cn=Directory Manager'` but may be solved with YAML configuration file use

It seems there is a little copy/paste error mapping on this `interval` field ,`ldap_389ds_scrape_interval` is the right variable isn't it ?

**Comment by ggatward** [comment]
Hi - wow that was fast, only pushed the role yesterday ;-)   Yep well spotted, copy-n-paste error indeed, now fixed in #7b202f2

Cheers
